#!/bin/bash
#author@sagarkar10
#This script clicks your webcam when ever called for along with the twicks in pam.d drive

file_path=`/var/tmp` 
#change if you dont want them in ut 'var/tmp' folder, give the desired path

ts=`date +%s`
ffmpeg -f video4linux2 -s vga -i /dev/video0 -vframes 1 $file_path/vid-$ts.%01d.jpg
exit 0  #important - has to exit with status 0
